---
abstract: 'Extract namespaces/version from traditional packages for provides'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Module::Metadata: '1.000022'
  Path::Tiny: '0'
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::Moose: '0'
  Test::More: '0.96'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.047, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-MetaProvides-Package
no_index:
  directory:
    - corpus
    - t/lib
provides:
  Dist::Zilla::Plugin::MetaProvides::Package:
    file: lib/Dist/Zilla/Plugin/MetaProvides/Package.pm
    version: '2.004001'
recommends:
  Moose: '2.000'
requires:
  Data::Dump: '1.16'
  Dist::Zilla: '5.000'
  Dist::Zilla::MetaProvides::ProvideRecord: '1.14000000'
  Dist::Zilla::Plugin::FinderCode: '0'
  Dist::Zilla::Plugin::MetaProvides: '1.15000000'
  Dist::Zilla::Role::MetaProvider::Provider: '0'
  Dist::Zilla::Role::ModuleMetadata: '0'
  Dist::Zilla::Role::PPI: '0'
  Moose: '0'
  MooseX::LazyRequire: '0'
  MooseX::Types::Moose: '0'
  PPI::Document: '0'
  Safe::Isa: '0'
  namespace::autoclean: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-MetaProvides-Package/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-MetaProvides-Package
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-MetaProvides-Package.git
version: '2.004001'
